version: '3'
services:
  go-monitor-1:
    build:
      dockerfile: Dockerfile
      context: ./go-monitor
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080:8080"
    # depends_on:
    #   - redis
    #   - influxdb
    environment:
      # - REDIS_HOST=redis
      # - INFLUXDB_HOST=influxdb
      - monitor_ID=1
  go-monitor-2:
    build:
      dockerfile: Dockerfile
      context: ./go-monitor
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8081:8080"
    # depends_on:
      # - redis
      # - influxdb
    environment:
      # - REDIS_HOST=redis
      # - INFLUXDB_HOST=influxdb
      - monitor_ID=2
  go-monitor-3:
    build:
      dockerfile: Dockerfile
      context: ./go-monitor
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8082:8080"
    # depends_on:
    #   - redis
    #   - influxdb
    environment:
      # - REDIS_HOST=redis
      # - INFLUXDB_HOST=influxdb
      - monitor_ID=3
#   redis:
#     image: "redis:alpine"
#     ports:
#       - "6379:6379"
#   influxdb:
#     image: influxdb:latest
#     ports:
#       - "8086:8086"
#     volumes:
#       - influxdb-data:/var/lib/influxdb

# volumes:
#   influxdb-data: